{% set version = "0.4.10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidygate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidygate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidygate/tidygate_{{ version }}.tar.gz
  sha256: 5ff3d0e93e0a6462ad2d82ddd8187b830d99e9246ed02ee448043a503fa3de10

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-dplyr
    - r-lifecycle
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-scales
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-viridis
  run:
    - r-base
    - r-rcolorbrewer
    - r-dplyr
    - r-lifecycle
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-scales
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-viridis

test:
  commands:
    - $R -e "library('tidygate')"           # [not win]
    - "\"%R%\" -e \"library('tidygate')\""  # [win]

about:
  home: https://github.com/stemangiola/tidygate
  license: GPL-3.0-only
  summary: It interactively or programmatically label points within custom gates on two dimensions <https://github.com/stemangiola/tidygate>. The information is added to your tibble. It is based on the package 'gatepoints' from Wajid Jawaid (who is also author of this package). The code of 'gatepoints' was nto integrated
    in 'tidygate'. The benefits are (i) in interactive mode you can draw your gates on extensive 'ggplot'-like scatter plots; (ii) you can draw multiple gates; and (iii) you can save your gates and apply the programmatically.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler

# Package: tidygate
# Type: Package
# Title: Add Gate Information to Your Tibble
# Version: 0.4.9
# Authors@R: c(person(given = "Stefano", family = "Mangiola", role = c("aut", "cre"), email = "mangiolastefano@gmail.com"), person(given = "Wajid", family = "Jawaid", role = "ctb"))
# Maintainer: Stefano Mangiola <mangiolastefano@gmail.com>
# Description: It interactively or programmatically label points within custom gates on two dimensions <https://github.com/stemangiola/tidygate>. The information is added to your tibble. It is based on the package 'gatepoints' from Wajid Jawaid (who is also author of this package). The code of 'gatepoints' was nto integrated in 'tidygate'. The benefits are (i) in interactive mode you can draw your gates on extensive 'ggplot'-like scatter plots; (ii) you can draw multiple gates; and (iii) you can save your gates and apply the programmatically.
# License: GPL-3
# Depends: R (>= 3.6.0)
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.2
# Imports: utils, graphics, lifecycle, scales, magrittr, tibble, dplyr, purrr, rlang, tidyr, viridis, grDevices, RColorBrewer, stringr
# RdMacros: lifecycle
# Suggests: testthat, markdown, knitr
# VignetteBuilder: knitr
# Biarch: true
# URL: https://github.com/stemangiola/tidygate
# BugReports: https://github.com/stemangiola/tidygate/issues
# NeedsCompilation: no
# Packaged: 2022-01-20 12:07:21 UTC; mangiola.s
# Author: Stefano Mangiola [aut, cre], Wajid Jawaid [ctb]
# Repository: CRAN
# Date/Publication: 2022-01-20 12:40:02 UTC
