{% set version = "1.0.13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidygate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidygate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidygate/tidygate_{{ version }}.tar.gz
  sha256: 8aac95903d1d11a3ebd5531f4ecc55e0dcc1e7a336761df198dbc591c260f0c5

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-lifecycle
    - r-magrittr
    - r-plotly
    - r-purrr
    - r-rcolorbrewer
    - r-rlang
    - r-scales
    - r-shiny
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-viridis
  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-lifecycle
    - r-magrittr
    - r-plotly
    - r-purrr
    - r-rcolorbrewer
    - r-rlang
    - r-scales
    - r-shiny
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-viridis

test:
  commands:
    - $R -e "library('tidygate')"           # [not win]
    - "\"%R%\" -e \"library('tidygate')\""  # [win]

about:
  home: https://github.com/stemangiola/tidygate
  license: GPL-3.0-only
  summary: It interactively or programmatically label points within custom gates on two dimensions <https://github.com/stemangiola/tidygate>. The information is added to your tibble. It is based on the package 'gatepoints' from Wajid Jawaid (who is also author of this package). The code of 'gatepoints' was nto integrated
    in 'tidygate'. The benefits are (i) in interactive mode you can draw your gates on extensive 'ggplot'-like scatter plots; (ii) you can draw multiple gates; and (iii) you can save your gates and apply the programmatically.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
